---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aws-peering-connection-operator.fullname" . }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
